export default {
  WORKSHOP_START: '// WORKSHOP_START\n',
  WORKSHOP_END: '\n// WORKSHOP_END',
  FINAL_START: '// FINAL_START\n',
  FINAL_END: '\n// FINAL_END',
  COMMENT_START: '// COMMENT_START\n',
  COMMENT_END: '\n// COMMENT_END'
};
